name: ovbot

on:
  schedule:
    - cron:  '1 12 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Build
        run: |
          sudo apt-get -q update
          sudo apt-get install openjdk-11-jdk
          ./CI/build.sh
